# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 20:26
from __future__ import unicode_literals

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0030_auto_20170508_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='_private_key',
            field=djstripe.fields.StripeCharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=djstripe.fields.StripeCharField(default='', help_text='The country of the account.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=djstripe.fields.StripeCharField(default='USD', help_text='Three-letter ISO currency code.', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='display_name',
            field=djstripe.fields.StripeCharField(blank=True, help_text='The display name for this account. This is used on the Stripe dashboard to help you differentiate between accounts.', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=djstripe.fields.StripeEmailField(blank=True, help_text='The primary user’s email address.', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='external_accounts',
            field=djstripe.fields.StripeJSONField(blank=True, help_text='External accounts (bank accounts and/or cards) currently attached to this account.'),
        ),
        migrations.AddField(
            model_name='account',
            name='legal_entity',
            field=djstripe.fields.StripeJSONField(blank=True, help_text='Information regarding the owner of this account, including verification status.'),
        ),
        migrations.AddField(
            model_name='account',
            name='managed',
            field=djstripe.fields.StripeBooleanField(default=False, help_text='Whether or not the account is managed by your platform. .'),
        ),
        migrations.AddField(
            model_name='account',
            name='public_key',
            field=djstripe.fields.StripeCharField(blank=True, max_length=255),
        ),
    ]
