# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0031_auto_20170511_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='account',
            field=models.ForeignKey(help_text='The account associated with this subscription.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='djstripe.Account'),
        ),
    ]
