# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-08 20:25
from __future__ import unicode_literals

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0032_subscription_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='external_accounts',
            field=djstripe.fields.StripeJSONField(blank=True, help_text='External accounts (bank accounts and/or cards) currently attached to this account.', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='legal_entity',
            field=djstripe.fields.StripeJSONField(blank=True, help_text='Information regarding the owner of this account, including verification status.', null=True),
        ),
    ]
